# Generated by Django 2.2.3 on 2019-07-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cuisines', models.TextField()),
                ('featured_image', models.URLField(max_length=250)),
                ('average_cost_for_two', models.DecimalField(decimal_places=2, max_digits=4)),
                ('thumb', models.URLField(max_length=250)),
                ('aggregate_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rating_text', models.CharField(max_length=30)),
                ('votes', models.IntegerField(max_length=4)),
            ],
        ),
    ]
