# Generated by Django 2.2.3 on 2019-07-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='zomato_id',
            field=models.IntegerField(default=None, max_length=10, unique=True),
        ),
    ]
