# Generated by Django 2.2.3 on 2019-07-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_restaurant_zomato_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='votes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zomato_id',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
