# Generated by Django 2.2.3 on 2019-07-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190728_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='aggregate_rating',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_cost_for_two',
            field=models.CharField(max_length=4),
        ),
    ]
