# Generated by Django 2.2.3 on 2019-07-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190728_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='average_cost_for_two',
            field=models.FloatField(default=0.0),
        ),
    ]
