# Generated by Django 2.2.3 on 2019-07-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190728_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
