# Generated by Django 2.2.3 on 2019-07-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20190728_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleRestaurants',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('types', models.TextField()),
                ('google_place_id', models.CharField(default=None, max_length=40)),
                ('average_cost_for_two', models.FloatField(default=0.0)),
                ('rating', models.CharField(max_length=4)),
                ('contact', models.CharField(max_length=20)),
                ('user_ratings_total', models.IntegerField()),
                ('vicinity', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameModel(
            old_name='ZomatoRestaurant',
            new_name='ZomatoRestaurants',
        ),
    ]
