# Generated by Django 2.2.3 on 2019-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20190728_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlerestaurants',
            name='price_level',
            field=models.IntegerField(default=None),
        ),
    ]
