# Generated by Django 2.2.3 on 2019-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_googlerestaurants_price_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlerestaurants',
            name='average_cost_for_two',
        ),
        migrations.AlterField(
            model_name='googlerestaurants',
            name='contact',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
