# Generated by Django 2.2.3 on 2019-07-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20190728_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlerestaurants',
            name='contact',
        ),
    ]
