# Generated by Django 2.2.3 on 2019-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_googlerestaurants_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlerestaurants',
            name='price_level',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
