# Generated by Django 2.2.3 on 2019-07-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20190730_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlerestaurants',
            name='contact',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='googlerestaurants',
            name='website',
            field=models.URLField(default=None, max_length=250),
        ),
    ]
