# Generated by Django 2.2.3 on 2019-07-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20190731_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlerestaurants',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='googlerestaurants',
            name='long',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='zomatorestaurants',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='zomatorestaurants',
            name='long',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
    ]
